app:
    resource: '@AppBundle/Controller/'
    type: annotation

connexion:
    defaults: { _controller: AppBundle:Dresseur:login }
    path: /connexion

deconnexion:
    defaults: { _controller: AppBundle:Dresseur:deconnexion }
    path: /deconnexion

inscription:
    defaults: { _controller: AppBundle:Dresseur:inscription }
    path: /inscription

pokemons:
    defaults: { _controller: AppBundle:Dresseur:getPokemons }
    path: /pokemons

pokemon:
    defaults: { _controller: AppBundle:Dresseur:getPokemon }
    path: /pokemons/pokemon/{id}

entrainer:
    defaults: { _controller: AppBundle:Dresseur:entrainerPokemon }
    path: /pokemons/pokemon/{id}/entrainer

mettre_en_vente:
    defaults: { _controller: AppBundle:Dresseur:mettreEnVentePokemon }
    path: /pokemons/pokemon/{id}/mettre_en_vente

annuler_vente:
    defaults: { _controller: AppBundle:Dresseur:annulerVentePokemon }
    path: /pokemons/pokemon/{id}/annuler_vente

annonces:
    defaults: { _controller: AppBundle:Annonces:get }
    path: /pokemons/annonces

acheter:
    defaults: { _controller: AppBundle:Dresseur:acheterPokemon }
    path: /pokemons/annonces/acheter/{id}