# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:Dresseur
                property: login
       # in_memory:
        #    memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: connexion
                check_path: connexion
                default_target_path: pokemons
                always_use_default_target_path: true

            logout:
                path: /deconnexion
                target: /

            provider: our_db_provider

    access_control:
          - { path: ^/admin, roles: ROLE_ADMIN }
          - { path: ^/pokemons, roles: [ROLE_USER, ROLE_ADMIN] }

    encoders:
        AppBundle\Entity\Dresseur:
            algorithm: plaintext